version: "3.9"

services:
  postgres-db:
    image: postgres:16
    container_name: my_postgres_bootcamp
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  pg_admin:
    image: dpage/pgadmin4:latest
    container_name: my_pgadmin_bootcamp
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "8080:80"

  metabase-app:
    image: metabase/metabase
    container_name: my_metabase_bootcamp
    restart: unless-stopped
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: postgres
      MB_DB_PORT: 5432
      MB_DB_USER: myuser
      MB_DB_PASS: mypassword
      MB_DB_HOST: postgres-db
    ports:
      - 4000:3000
    volumes:
      - ./metabase-data:/metabase-data
    depends_on:
      - postgres-db
    links:
      - postgres-db

volumes:
  pgdata:
    name: pgdata
  metabase-data:
    name: metabase-data
